### ISSUE TITLE
Unable to Install the app

### ISSUE THREAD

**Issue by SangramChavan** [AhmedAshour/skiller-student#1]
Hey, The apk displays an error while installing the app.

**Comment by AhmedAshour** [comment]
Check this one:
[app-release.zip](https://github.com/AhmedAshour/skiller-student/files/4516275/app-release.zip)
@SangramChavan

**Comment by SangramChavan** [comment]
The app still now working.

**Comment by SangramChavan** [comment]
Hii, your app is one of the potential winner app but the last zip containing the apk does not work. 
Please share the apks again sharing both the apks and it would be great if we have some from the team in contact while testing the app.

**Comment by AhmedAshour** [comment]
Sorry didn't notice the comment, I will export another apk now. Can we talk in another channel for easier testing?

**Comment by SangramChavan** [comment]
If you can contact on WhatsApp it would be easier.
You may reach out at +447415595537
